vim.pack.add({
    'https://github.com/nvim-lua/plenary.nvim',
    'https://github.com/nvim-treesitter/nvim-treesitter',
    'https://github.com/nvim-telescope/telescope-fzf-native.nvim',
    'https://github.com/nvim-telescope/telescope-ui-select.nvim',
    'https://github.com/MunifTanjim/nui.nvim',
    'https://github.com/windwp/nvim-autopairs',
    'https://github.com/rafamadriz/friendly-snippets',
    "https://github.com/nvim-tree/nvim-web-devicons",
    "https://github.com/pmizio/typescript-tools.nvim",
})
