vim.pack.add({ 'https://github.com/max397574/startup.nvim' })
require('startup').setup {
    header = {
        type = 'text',
        oldfiles_directory = false,
        align = 'center',
        fold_section = false,
        title = 'Header',
        margin = 5,
        content = {
            '███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗     ██████╗  ██████╗ ██╗  ██╗  ██╗',
            '████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║     ██╔══██╗   ██╔═╝ ██║  ██║  ██║',
            '██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║     ██████╔╝   ██║   ██║  ██║  ██║',
            '██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║     ██╔══██╗   ██║   ╚██╗ ██║ ██╔╝',
            '██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║     ██████╔╝   ██║    ╚████████╔╝ ',
            '╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝     ╚═════╝    ╚═╝     ╚═══════╝  ',
        },
        highlight = 'String',
        default_color = '',
        oldfiles_amount = 0,
    },
    -- name which will be displayed and command
    header_2 = {
        type = 'text',
        oldfiles_directory = false,
        align = 'center',
        fold_section = false,
        title = 'Quote',
        margin = 5,
        content = require('startup.functions').quote(),
        highlight = 'String',
        default_color = '',
        oldfiles_amount = 0,
    },
    logo = {
        type = 'text',
        align = 'center',
        fold_section = false,
        title = 'Header',
        margin = 5,
        content = require('startup.headers').hydra_header,
        highlight = 'Statement',
        default_color = '',
        oldfiles_amount = 0,
    },
    footer = {
        type = 'text',
        oldfiles_directory = false,
        align = 'center',
        fold_section = false,
        title = 'Footer',
        margin = 5,
        content = { 'Made with startup.nvim :D' },
        highlight = 'Number',
        default_color = '',
        oldfiles_amount = 0,
    },

    options = {
        mapping_keys = false,
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = { 1, 2, 3, 2, 0 },
    },
    mappings = {
        execute_command = '<CR>',
        open_file = 'o',
        open_file_split = '<c-o>',
        open_section = '<TAB>',
        open_help = '?',
    },
    colors = {
        background = '#1f2227',
        folded_section = '#56b6c2',
    },
    parts = { 'header', 'header_2', 'logo', 'footer' },
}
